### ISSUE TITLE
server group icons

### ISSUE THREAD

**Issue by codiii** [LeoWinterDE/TS3ServerStatusViewer#2]
As of now it only shows server admins icons etc... is there any is there any way to get channel icons and custom server groups to shows also? I am willing to donate

**Comment by leowinterde** [comment]
Custom group icons are shown if you put the icon file in the folder `/img/default/group_<Group ID>.png`. But display custom channel icons is not yet implemented.

Currently I have no time to work on this, sorry, Maybe you'll find someone else.

**Comment by SvenC56** [comment]
I like to add that some icons are not displayed. It shows 4 of my like 10 custom icons...

**Comment by tribut** [comment]
This is likely fixed by #3.
