### ISSUE TITLE
setting. setup.php

### ISSUE THREAD

**Issue by RewLoad** [LeoWinterDE/TS3ServerStatusViewer#7]
I'm very confused about the setting. setup.php
Do you have a complete setup example?
![image](https://user-images.githubusercontent.com/50944833/155918191-e86e14c6-86b5-4907-8477-2688f4c083df.png)

**Comment by leowinterde** [comment]
Just access the setup.php in your browser. You don't have to adjust anything yourself, besides `$enableGenerator = true;`

Or just follow https://github.com/LeoWinterDE/TS3ServerStatusViewer#download-install
